author: Heitor Gouvêa
title: Heitor Gouvêa
url: "http://heitorgouvea.me"
og_image: /images/heitorgouvea.jpg
baseurl: ""

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
