title: Heitor Gouvêa
url: "https://heitorgouvea.me"
baseurl: ""
og_image: https://heitorgouvea.me/images/photos/heitor-gouvea.png
twitter_username: '@GouveaHeitor'
markdown: kramdown
desc: "I just create things I need to see exist in the world"
author: "@GouveaHeitor"
tracking_id: UA-105655736-1

footer: yes
footer_url: "https://heitorgouvea.me"
footer_text: "© 2019 Heitor Gouvêa. All rights reserved. "

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about"
