# Site settings
title: Heitor Gouvea - Researcher Biohacking - heitorgouvea.me
email: hi@heitorgouvea.me
description: >
  Hi, I'm Heitor Gouvea. I am Web Developer Full Stack in a awesome company on Brazil.
baseurl: ""
url: "http://heitorgouvea.me/blog/"
twitter_username: GouveaHeitor
github_username:  HeitorG

# Build settings
markdown: kramdown