title: Heitor Gouvêa
description: >
    I work with amazing companies on projects that help people, organizations, and companies take control of their own information.
keywords: Heitor Gouvêa, Security Researcher, Independent, Freelancer, Pentester, Bug Bounty Hunter, Perl, Fuzzing, Nipe, Nozaki, Uranus, 
author: Heitor Gouvêa
email: hi@heitorgouvea.me
baseurl: "" 
url: "https://heitorgouvea.me" 

twitter_username: x86scale
github_username:  x86scale

include: [_pages]
exclude: ["README.md", "SECURITY.md", "LICENSE.md", "Gemfile", "Dockerfile"]

markdown: kramdown
permalink: /:year/:month/:day/:title

sass:
    style: compressed
gems:
  - jemoji
  - jekyll-sitemap

google_analytics: UA-105655736-1