author: Heitor Gouvêa
title: Heitor Gouvêa
url: "https://heitorgouvea.me"
enforce_ssl: www.heitorgouvea.me
og_image: /images/heitorgouvea.png
description: Hi! My name is Heitor Gouvêa and I am an Cybersecurity Engineer and Instructor from Brazil. I have been working on projects that help people, organizations and companies take control of their own security.
baseurl: ""

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
