author: Heitor Gouvêa
title: Heitor Gouvêa
url: "http://heitorgouvea.me"
og_image: /images/heitorgouvea.jpg
description: Hi! My name is Heitor Gouvêa and I am an Information Security Specialist, working how Information Security Lead at Inploit Security. I have working on projects that help people, organizations and companies take control of their own security.
baseurl: ""

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
