author: Heitor Gouvêa
title: Heitor Gouvêa
url: "https://heitorgouvea.me"
enforce_ssl: www.heitorgouvea.me
og_image: /images/heitorgouvea.jpg
description: Hi! My name is Heitor Gouvêa and I am an independent Information Security Researcher.
baseurl: ""

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
