author: Heitor Gouvêa
title: Heitor Gouvêa
url: "http://heitorgouvea.me"
baseurl: "/"
og_image: "/images/heitorgouvea.jpg"
twitter_username: @GouveaHeitor

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
