title: Heitor Gouvêa
description: >
    I work with amazing companies on projects that help people, organizations, and companies take control of their own information.
keywords: Heitor Gouvêa, Independent, Security Researcher, Pentester, Nipe
author: Heitor Gouvêa
email: hi@heitorgouvea.me
baseurl: "" 
url: "https://heitorgouvea.me" 
twitter_username: GouveaHeitor
github_username:  GouveaHeitor
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:day/:title
sass:
    style: compressed
gems:
  - jemoji
  - jekyll-sitemap
google_analytics: UA-105655736-1