author: Heitor Gouvêa
title: Heitor Gouvêa
url: "http://heitorgouvea.me"
og_image: /images/heitorgouvea.jpg
description: Hi! My name is Heitor Gouvêa and I am an Information Security Reseacher, working as independet Information Security Consultant.  
baseurl: ""

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
