# Site settings
title: Heitor Gouvea - Web Developer Full Stack - heitorgouvea.me
email: hi@heitorgouvea.me
description: >

baseurl: "http://heitorgouvea.me/blog/"
url: "http://heitorgouvea.me/blog/"
twitter_username: GouveaHeitor
github_username:  HeitorG

# Build settings
markdown: kramdown