name: Insider OSS

on: 
  push:
    branches: 
      - develop

jobs:
  insider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Insider
        uses: insidersec/insider-action@v0
        with:
            technology: javascript
            target: ${{ GITHUB_WORKSPACE }}